import type { Metadata } from "next";
import { UserProvider } from '@auth0/nextjs-auth0/client'
import { Inter as FontSans } from "next/font/google"
import "@/styles/globals.css";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <UserProvider>
        <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
          <main className="flex min-h-screen flex-col items-center justify-center">
            {children}
          </main>
        </body>
      </UserProvider>
    </html>
  );
}
